apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_USER: ""
  MYSQL_PASSWORD: ""
  DB_CONN: "Server=mysql-service;Port=3306;Database=LeadDB;User=;Password=;"
  JWT_KEY: ""
