apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_USER: "aishwarya"
  MYSQL_PASSWORD: "Ganesha-123456"
  DB_CONN: "Server=mysql-service;Port=3306;Database=LeadDB;User=aishwarya;Password=Ganesha-123456;"
  JWT_KEY: "ThisIsASecretKeyForJwtTokenGeneration"
